apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rhobs-thanos-bucket-inspect-cron
  labels:
    app.kubernetes.io/name: thanos-bucket-inspect
    app.kubernetes.io/part-of: observatorium
description: |
  Inspect data in an object storage provider bucket on a schedule
parameters:
  - name: NAME
    description: The name of the CronJob.
    value: 'thanos-bucket-inspect'
  - name: NAMESPACE
    description: The namespace where the Job should run.
    value: 'observatorium-operations'
  - name: OBJ_STORE_CONFIG_SECRET_NAME
    value: 'thanos-bucket-inspect-config'
  - name: K8S_SECRET_KEY
    value: config.yaml
  - name: SCHEDULE
    description: The schedule for the Job to run. Defaults to every 12 hours.
    value: '0 */12 * * *'
  - name: TENANT_ID
    value: 'rhobs'
  - name: IMAGE_TAG
    value: 'v0.31.0'
  - name: LOG_LEVEL
    value: 'info'
objects:
  - apiVersion: batch/v1
    kind: CronJob
    metadata:
      name: ${NAME}
      namespace: ${NAMESPACE}
      labels:
        app.kubernetes.io/name: thanos-bucket-inspect
        app.kubernetes.io/part-of: observatorium
    spec:
      schedule: ${SCHEDULE}
      jobTemplate:
        spec:
          template:
            spec:
              containers:
                - name: thanos-bucket-inspect
                  image: quay.io/thanos/thanos:${IMAGE_TAG}
                  volumeMounts:
                    - name: obj-store-config
                      readOnly: true
                      mountPath: "/var/lib/thanos/bucket-inspect-config"
                  args:
                    - 'tools'
                    - 'bucket'
                    - 'inspect'
                    - '--log.level=${LOG_LEVEL}'
                    - '--objstore.config-file=/var/lib/thanos/bucket-inspect-config/${K8S_SECRET_KEY}'
                    - '--selector=tenant_id="${TENANT_ID}"'
              restartPolicy: Never
              volumes:
                - name: obj-store-config
                  secret:
                    secretName: ${OBJ_STORE_CONFIG_SECRET_NAME}

