apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: rclone Bucket Sync
  labels:
    app.kubernetes.io/name: rclone-config
    app.kubernetes.io/part-of: observatorium
description: |
  This template creates a Secret that supports general configuration.
parameters:
  - name: NAMESPACE
    description: The namespace where the ConfigMap will be created.
    value: 'observatorium-operations'
  - name: RCLONE_CONFIG_MAP_NAME
    value: 'rclone-config'
  - name: RCLONE_STATS_INTERVAL
    value: '30s'
  - name: RCLONE_LOG_LEVEL
    value: 'INFO'
  - name: RCLONE_PARALLEL_TRANSFERS
    value: '4'
  - name: RCLONE_PARALLEL_FILE_CHECKERS
    value: '8'
  - name: RCLONE_S3_UPLOAD_CONCURRENCY
    value: '8'
  - name: RCLONE_S3_CHUNK_SIZE
    value: '64M'
  - name: RCLONE_MULTI_THREAD_STREAMS
    value: '8'

objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${RCLONE_CONFIG_MAP_NAME}
      namespace: ${NAMESPACE}
      labels:
        app.kubernetes.io/name: rclone-bucket-replicate-secret
        app.kubernetes.io/part-of: observatorium
    data:
      # Logging configuration
      RCLONE_STATS: ${RCLONE_STATS_INTERVAL}
      RCLONE_LOG_LEVEL: ${RCLONE_LOG_LEVEL}

      # Number of file transfers to run in parallel
      RCLONE_TRANSFERS: ${RCLONE_PARALLEL_TRANSFERS}

      # Number of parallel download threads
      RCLONE_MULTI_THREAD_STREAMS: ${RCLONE_MULTI_THREAD_STREAMS}

      # Checkers do the equality checking of files during a sync
      RCLONE_CHECKERS: ${RCLONE_PARALLEL_FILE_CHECKERS}

      # AWS Client Specific Parameters
      RCLONE_S3_UPLOAD_CONCURRENCY: ${RCLONE_S3_UPLOAD_CONCURRENCY}
      RCLONE_S3_CHUNK_SIZE: ${RCLONE_S3_CHUNK_SIZE}

