---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: observatorium-gubernator-stage
spec:
  groups:
  - name: gubernator-absent
    rules:
    - alert: gubernatorIsDown
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/no-dashboard/gubernator-absent?orgId=1&refresh=10s&var-datasource=app-sre-stage-01-prometheus&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
        message: gubernator has disappeared from Prometheus target discovery.
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#gubernatorisdown
      expr: |
        absent(up{job="observatorium-gubernator"} == 1)
      for: 5m
      labels:
        service: telemeter
        severity: high
