---
$schema: /app-interface/prometheus-rule-test-1.yml

rule_files:
- /observability/prometheusrules/observatorium-api-stage.prometheusrules.yaml

evaluation_interval: 1m

tests:
- interval: 1m
  input_series:
  - series: http_requests_total:burnrate5m{group="metricsv1",handler="receive",job="observatorium-observatorium-api"}
    values: '0 0 0 0 0 0 1 1 1'
  - series: http_requests_total:burnrate1h{group="metricsv1",handler="receive",job="observatorium-observatorium-api"}
    values: '0 0 0 0 0 0 1 1 1'
  alert_rule_test:
    # Alert is the same, but fired across various time ranges.
  - eval_time: 4m
    alertname: ObservatoriumAPIMetricsErrorsSLOBudgetBurn
  - eval_time: 5m
    alertname: ObservatoriumAPIMetricsErrorsSLOBudgetBurn
  - eval_time: 10m
    alertname: ObservatoriumAPIMetricsErrorsSLOBudgetBurn
    exp_alerts:
    - exp_labels:
        handler: receive
        job: observatorium-observatorium-api
        service: telemeter
        severity: high # critical for production
      exp_annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADX/observatorium-api-write-metrics-errors.slo?orgId=1&refresh=10s&var-datasource=app-sre-stage-01-prometheus&var-namespace=&var-job=All&var-pod=All&var-interval=5m
        message: 'High error budget burn for group=metricsv1,handler=receive,job=observatorium-observatorium-api (current value: 1)'
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#observatoriumapimetricserrorsslobudgetburn