---
$schema: /openshift/prometheus-rule-1.yml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: app-sre
    role: alert-rules
  name: rhobs-slos-telemeter-stage
spec:
  groups:
  - name: telemeter-server-metrics-write-availability.slo
    rules:
    - alert: TelemeterServerMetricsWriteAvailabilityErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter Server /upload or /receive is burning too much error budget to gurantee availability SLOs
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/telemeter.md#telemeterservermetricswriteavailabilityerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate5m{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (14.40 * (1-0.95000))
        and
        sum(haproxy_server_http_responses_total:burnrate1h{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (14.40 * (1-0.95000))
      for: 2m
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
        service: telemeter
        severity: high
    - alert: TelemeterServerMetricsWriteAvailabilityErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter Server /upload or /receive is burning too much error budget to gurantee availability SLOs
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/telemeter.md#telemeterservermetricswriteavailabilityerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate30m{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (6.00 * (1-0.95000))
        and
        sum(haproxy_server_http_responses_total:burnrate6h{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (6.00 * (1-0.95000))
      for: 15m
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
        service: telemeter
        severity: high
    - alert: TelemeterServerMetricsWriteAvailabilityErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter Server /upload or /receive is burning too much error budget to gurantee availability SLOs
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/telemeter.md#telemeterservermetricswriteavailabilityerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate2h{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (3.00 * (1-0.95000))
        and
        sum(haproxy_server_http_responses_total:burnrate1d{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (3.00 * (1-0.95000))
      for: 1h
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
        service: telemeter
        severity: medium
    - alert: TelemeterServerMetricsWriteAvailabilityErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: Telemeter Server /upload or /receive is burning too much error budget to gurantee availability SLOs
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/telemeter.md#telemeterservermetricswriteavailabilityerrorbudgetburning
      expr: |
        sum(haproxy_server_http_responses_total:burnrate6h{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (1.00 * (1-0.95000))
        and
        sum(haproxy_server_http_responses_total:burnrate3d{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}) > (1.00 * (1-0.95000))
      for: 3h
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
        service: telemeter
        severity: medium
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[1d]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[1d]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate1d
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[1h]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[1h]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate1h
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[2h]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[2h]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate2h
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[30m]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[30m]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate30m
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[3d]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[3d]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate3d
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[5m]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[5m]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate5m
    - expr: |
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx",code="5xx"}[6h]))
        /
        sum(rate(haproxy_server_http_responses_total{route=~"telemeter-server-upload|telemeter-server-metrics-v1-receive",code!="4xx"}[6h]))
      labels:
        code!: 4xx
        route: telemeter-server-upload|telemeter-server-metrics-v1-receive
      record: haproxy_server_http_responses_total:burnrate6h
  - name: telemeter-server-metrics-write-latency.slo
    rules:
    - alert: TelemeterServerMetricsWriteLatencyErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: 'High requests latency budget burn for job=telemeter-server,handler=~upload|receive,code=~^(2..|3..|5..),latency=5 (current value: {{ $value }})'
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/telemeter.md#telemeterservermetricswritelatencyerrorbudgetburning
      expr: |
        (
          latencytarget:http_request_duration_seconds:rate1h{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (14.4*0.900000)
          and
          latencytarget:http_request_duration_seconds:rate5m{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (14.4*0.900000)
        )
        or
        (
          latencytarget:http_request_duration_seconds:rate6h{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (6*0.900000)
          and
          latencytarget:http_request_duration_seconds:rate30m{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (6*0.900000)
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
        service: telemeter
        severity: high
    - alert: TelemeterServerMetricsWriteLatencyErrorBudgetBurning
      annotations:
        dashboard: https://grafana.app-sre.devshift.net/d/Tg-mH0rizaSJDKSADJ/telemeter?orgId=1&refresh=1m&var-datasource=app-sre-stage-01-prometheus
        message: 'High requests latency budget burn for job=telemeter-server,handler=~upload|receive,code=~^(2..|3..|5..),latency=5 (current value: {{ $value }})'
        runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/telemeter.md#telemeterservermetricswritelatencyerrorbudgetburning
      expr: |
        (
          latencytarget:http_request_duration_seconds:rate1d{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (3*0.900000)
          and
          latencytarget:http_request_duration_seconds:rate2h{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (3*0.900000)
        )
        or
        (
          latencytarget:http_request_duration_seconds:rate3d{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (0.900000)
          and
          latencytarget:http_request_duration_seconds:rate6h{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",latency="5"} > (0.900000)
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
        service: telemeter
        severity: medium
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[5m]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[5m]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate5m
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[30m]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[30m]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate30m
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[1h]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[1h]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate1h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[2h]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[2h]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate2h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[6h]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[6h]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate6h
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[1d]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[1d]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate1d
    - expr: |
        1 - (
          sum(rate(http_request_duration_seconds_bucket{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)",le="5",code!~"5.."}[3d]))
          /
          sum(rate(http_request_duration_seconds_count{job="telemeter-server",handler=~"upload|receive",code=~"^(2..|3..|5..)"}[3d]))
        )
      labels:
        code: ^(2..|3..|5..)
        handler: upload|receive
        job: telemeter-server
        latency: "5"
      record: latencytarget:http_request_duration_seconds:rate3d
