apiVersion: v1alpha1
kind: ServiceLevelObjective
metadata:
  annotations:
    pyrra.dev/dashboard: https://grafana.app-sre.devshift.net/d//rhelemeter-stage-slos?orgId=1&refresh=10s&var-datasource=&var-namespace={{$labels.namespace}}&var-job=All&var-pod=All&var-interval=5m
    pyrra.dev/message: Rhelemeter Server /receive is burning too much error budget
      to guarantee latency SLOs.
    pyrra.dev/runbook: https://github.com/rhobs/configuration/blob/main/docs/sop/observatorium.md#RhelemeterServerMetricsReceiveWriteLatencyErrorBudgetBurning
  creationTimestamp: null
  labels:
    pyrra.dev/service: rhelemeter
    route: rhelemeter-server-receive
  name: rhobs-rhelemeter-server-metrics-receive-latency-slo
spec:
  alerting:
    name: RhelemeterServerMetricsReceiveWriteLatencyErrorBudgetBurning
  description: Rhelemeter Server /receive is burning too much error budget to guarantee
    latency SLOs.
  indicator:
    latency:
      grouping: null
      success:
        metric: http_request_duration_seconds_bucket{job="rhelemeter-server", handler="receive",
          code=~"^2..$", le="5"}
      total:
        metric: http_request_duration_seconds_count{job="rhelemeter-server", handler="receive",
          code=~"^2..$"}
  target: "90"
  window: 28d
status: {}
