apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosCompact
metadata:
  creationTimestamp: null
  name: rhobs
  namespace: rhobs-local
spec:
  additionalArgs:
  - |-
    --tracing.config="config":
      "sampler_param": 2
      "sampler_type": "ratelimiting"
      "service_name": "thanos-compact"
    "type": "JAEGER"
  additionalContainers:
  - args:
    - --reporter.grpc.host-port=dns:///otel-trace-writer-collector-headless.observatorium-tools.svc:14250
    - --reporter.type=grpc
    - --agent.tags=pod.namespace=$(NAMESPACE),pod.name=$(POD)
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    image: quay.io/jaegertracing/jaeger-agent:1.57.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: 14271
        scheme: HTTP
      initialDelaySeconds: 1
    name: jaeger-agent
    ports:
    - containerPort: 5778
      name: configs
    - containerPort: 6831
      name: jaeger-thrift
    - containerPort: 14271
      name: metrics
    readinessProbe:
      httpGet:
        path: /
        port: 14271
        scheme: HTTP
      initialDelaySeconds: 1
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  compactConfig:
    compactConcurrency: 1
  debugConfig:
    acceptMalformedIndex: true
    haltOnError: true
    maxCompactionLevel: 3
  downsamplingConfig:
    downsamplingConcurrency: 1
    downsamplingEnabled: false
  featureGates:
    serviceMonitor:
      enable: false
  image: quay.io/thanos/thanos
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  logLevel: info
  objectStorageConfig:
    key: thanos.yaml
    name: default-objectstorage
    optional: false
  resourceRequirements:
    limits:
      cpu: 20m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 20Mi
  retentionConfig:
    fiveMinutes: 365d
    oneHour: 365d
    raw: 365d
  storageSize: 1Gi
  version: v0.37.2
status: {}
---
apiVersion: monitoring.thanos.io/v1alpha1
kind: ThanosCompact
metadata:
  creationTimestamp: null
  name: telemeter
  namespace: rhobs-local
spec:
  additionalArgs:
  - |-
    --tracing.config="config":
      "sampler_param": 2
      "sampler_type": "ratelimiting"
      "service_name": "thanos-compact"
    "type": "JAEGER"
  additionalContainers:
  - args:
    - --reporter.grpc.host-port=dns:///otel-trace-writer-collector-headless.observatorium-tools.svc:14250
    - --reporter.type=grpc
    - --agent.tags=pod.namespace=$(NAMESPACE),pod.name=$(POD)
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    image: quay.io/jaegertracing/jaeger-agent:1.57.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /
        port: 14271
        scheme: HTTP
      initialDelaySeconds: 1
    name: jaeger-agent
    ports:
    - containerPort: 5778
      name: configs
    - containerPort: 6831
      name: jaeger-thrift
    - containerPort: 14271
      name: metrics
    readinessProbe:
      httpGet:
        path: /
        port: 14271
        scheme: HTTP
      initialDelaySeconds: 1
    resources:
      limits:
        cpu: 128m
        memory: 128Mi
      requests:
        cpu: 32m
        memory: 64Mi
  compactConfig:
    compactConcurrency: 1
  debugConfig:
    acceptMalformedIndex: true
    haltOnError: true
    maxCompactionLevel: 3
  downsamplingConfig:
    downsamplingConcurrency: 1
    downsamplingEnabled: false
  featureGates:
    serviceMonitor:
      enable: false
  image: quay.io/thanos/thanos
  imagePullPolicy: IfNotPresent
  logFormat: logfmt
  logLevel: info
  objectStorageConfig:
    key: thanos.yaml
    name: telemeter-objectstorage
    optional: false
  resourceRequirements:
    limits:
      cpu: 20m
      memory: 50Mi
    requests:
      cpu: 10m
      memory: 20Mi
  retentionConfig:
    fiveMinutes: 365d
    oneHour: 365d
    raw: 365d
  storageSize: 1Gi
  version: v0.37.2
status: {}
