apiVersion: v1
kind: Template
metadata:
  name: conprof-observatorium-mst-rbac
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    labels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: conprof-${OBSERVATORIUM_MST_NAMESPACE}
    namespace: ${OBSERVATORIUM_MST_NAMESPACE}
  rules:
  - apiGroups:
    - ""
    resources:
    - services
    - endpoints
    - pods
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/instance: conprof
      app.kubernetes.io/name: conprof
      app.kubernetes.io/version: ${IMAGE_TAG}
    name: conprof-${OBSERVATORIUM_MST_NAMESPACE}
    namespace: ${OBSERVATORIUM_MST_NAMESPACE}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: conprof-${OBSERVATORIUM_MST_NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: ${SERVICE_ACCOUNT_NAME}
    namespace: ${NAMESPACE}
parameters:
- name: IMAGE_TAG
  value: master-2020-04-29-73bf4f0
- name: NAMESPACE
  value: observatorium
- name: OBSERVATORIUM_MST_NAMESPACE
  value: observatorium-mst
- name: SERVICE_ACCOUNT_NAME
  value: prometheus-telemeter
