apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    qontract.recycle: "true"
  name: ${CONFIGMAP_NAME}
objects:
- apiVersion: v1
  data:
    receive.limits.yaml: |-
      "write":
        "default":
          "head_series_limit": ${HEAD_SERIES_LIMIT}
          "request":
            "samples_limit": ${SAMPLES_LIMIT}
            "series_limit": ${SERIES_LIMIT}
            "size_bytes_limit": ${SIZE_BYTE_LIMIT}
        "global":
          "max_concurrency": ${MAX_CONCURRENCY}
          "meta_monitoring_limit_query": '${QUERY}'
          "meta_monitoring_url": "${META_MONITORING_URL}"
        "tenants":
          ${TENANT_ID}:
            "head_series_limit": ${TENANT_HEAD_SERIES_LIMIT}
  kind: ConfigMap
  metadata:
    annotations:
      qontract.recycle: "true"
    name: ${CONFIGMAP_NAME}
parameters:
- name: CONFIGMAP_NAME
- name: MAX_CONCURRENCY
  value: "0"
- name: META_MONITORING_URL
  value: http://prometheus-app-sre.openshift-customer-monitoring.svc.cluster.local:9090
- name: QUERY
  value: sum(prometheus_tsdb_head_series{namespace="observatorium-mst-stage"}) by (tenant)
- name: SIZE_BYTE_LIMIT
  value: "0"
- name: SERIES_LIMIT
  value: "5000"
- name: SAMPLES_LIMIT
  value: "5000"
- name: HEAD_SERIES_LIMIT
  value: "100000"
- name: TENANT_ID
  value: 1b9b6e43-9128-4bbf-bfff-3c120bbe6f11
- name: TENANT_HEAD_SERIES_LIMIT
  value: "10000000"
