apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: Thanos Bucket Inspect
  labels:
    app.kubernetes.io/name: thanos-bucket-replicate-secret
    app.kubernetes.io/part-of: observatorium
description: |
  This template creates a Secret that supports Thanos Object Storage for S3.
parameters:
  - name: NAMESPACE
    description: The namespace where the Secret will be created.
    value: 'observatorium-operations'
  - name: OBJ_STORE_CONFIG_SECRET_NAME
    value: 'thanos-bucket-config'
  - name: ACCESS_KEY_ID
  - name: SECRET_ACCESS_KEY
  - name: S3_BUCKET_NAME
  - name: S3_BUCKET_ENDPOINT
    value: s3.us-east-1.amazonaws.com
  - name: S3_BUCKET_REGION
    value: us-east-1
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${OBJ_STORE_CONFIG_SECRET_NAME}
      namespace: ${NAMESPACE}
      labels:
        app.kubernetes.io/name: thanos-bucket-replicate-secret
        app.kubernetes.io/part-of: observatorium
    type: Opaque
    stringData:
      config.yaml: |
        type: S3
        config:
          bucket: ${S3_BUCKET_NAME}
          region: ${S3_BUCKET_REGION}
          access_key: ${ACCESS_KEY_ID}
          secret_key: ${SECRET_ACCESS_KEY}
          endpoint: ${S3_BUCKET_ENDPOINT}


