name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: make grafana manifests prometheusrules
    - name: Format
      run: make format
    - name: Lint
      run: make Lint
    - name: Validate
      run: make validate
    - name: Diff
      run: git diff --exit-code
