apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: thanos-objectstorage
  name: thanos-objectstorage
  namespace: rhobs-local
stringData:
  thanos.yaml: |-
    type: S3
    config:
      bucket: thanos
      region: us-east-1
      access_key: minio
      secret_key: minio123
      endpoint: minio.observatorium-minio.svc:9000
      insecure: true
type: Opaque
